name: myPLatform_2
services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASES_NAME}
      POSTGRES_USER: ${DATABASES_USER}
      POSTGRES_PASSWORD: ${DATABASES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  django-web:
    image: yevheniy88/myplatform:gitactions 
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runscript add_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./static:/app/static/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web

volumes:
  pgdata:
