# Generated by Django 5.1.5 on 2025-02-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_office',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_retail',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_store',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='OfficePosition',
        ),
        migrations.DeleteModel(
            name='RetailPosition',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='StorePosition',
        ),
    ]
