# Generated by Django 5.1.5 on 2025-02-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_position_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeposition',
            old_name='position_office',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='retailposition',
            old_name='position_retail',
            new_name='position_name',
        ),
        migrations.RenameField(
            model_name='storeposition',
            old_name='position_store',
            new_name='position_name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_office',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_retail',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_store',
        ),
        migrations.AddField(
            model_name='officeposition',
            name='office_position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position'),
        ),
        migrations.AddField(
            model_name='retailposition',
            name='retail_position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position'),
        ),
        migrations.AddField(
            model_name='storeposition',
            name='store_position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position'),
        ),
    ]
