# Generated by Django 5.1.5 on 2025-02-04 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_position_office_officeposition_position_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='UserPosition',
        ),
    ]
