# Generated by Django 5.1.5 on 2025-02-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_position_userposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeposition',
            old_name='office_position',
            new_name='user_position',
        ),
        migrations.RenameField(
            model_name='retailposition',
            old_name='retail_position',
            new_name='user_position',
        ),
        migrations.RenameField(
            model_name='storeposition',
            old_name='store_position',
            new_name='user_position',
        ),
    ]
