# Generated by Django 5.1.5 on 2025-02-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_userposition_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeposition',
            old_name='user_position',
            new_name='user_office_position',
        ),
        migrations.RenameField(
            model_name='retailposition',
            old_name='user_position',
            new_name='user_retail_position',
        ),
        migrations.RenameField(
            model_name='storeposition',
            old_name='user_position',
            new_name='user_store_position',
        ),
    ]
