# Generated by Django 5.1.5 on 2025-02-04 22:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_rename_user_position_officeposition_user_office_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='UserInfo',
        ),
    ]
