# Generated by Django 5.1.5 on 2025-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeposition',
            name='position_name',
            field=models.CharField(choices=[('BK', 'Bookkeper'), ('LS', 'Logigstic Support'), ('IT', 'Sys Admin'), ('AU', 'Auditor')], max_length=50),
        ),
    ]
