# Generated by Django 5.1.5 on 2025-02-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_officeposition_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeposition',
            name='user_office_position',
        ),
        migrations.RemoveField(
            model_name='retailposition',
            name='user_retail_position',
        ),
        migrations.RemoveField(
            model_name='storeposition',
            name='user_store_position',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='OfficePosition',
        ),
        migrations.DeleteModel(
            name='RetailPosition',
        ),
        migrations.DeleteModel(
            name='StorePosition',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
