# Generated by Django 5.1.5 on 2025-02-17 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0016_remove_officeposition_user_office_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('DM', 'District Manager'), ('DMT', 'District Manager Tranee'), ('RMT', 'Region Manager Trainee'), ('RM', 'Region Manager'), ('CM', 'Country Manager')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfficePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('BKS', 'Store bookkeper'), ('BKL', 'Logistic bookkeper'), ('BKE', 'Employee bookkeper'), ('BKM', 'Main bookkeper'), ('LS', 'Logigstic Supporter'), ('IT', 'Sys Admin'), ('AU', 'Auditor'), ('FA', 'Facility')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegionPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('DM', 'District Manager'), ('DMT', 'District Manager Tranee'), ('RMT', 'Region Manager Trainee'), ('RM', 'Region Manager'), ('CM', 'Country Manager')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('SM', 'Store Manager'), ('SMT', 'Store Manager Trainee'), ('DepSm', 'DeputyStoreManager'), ('AR', 'Area Responsible'), ('LR', 'Logistic Responsible'), ('SA', 'Sails Assistens')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AllPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.districtpositions')),
                ('office_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.officepositions')),
                ('region_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.regionpositions')),
                ('store_posions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.storepositions')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.allpositions')),
            ],
        ),
        migrations.CreateModel(
            name='Emploee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employeeposition')),
            ],
        ),
    ]
