# Generated by Django 5.1.5 on 2025-02-17 14:39

import django.db.models.deletion
import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.allpositions'),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='district_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=employee.models.RetailPositionsChoises),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='office_positions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=employee.models.OfficePositionsChoises),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='region_positions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=employee.models.RetailPositionsChoises),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='store_posions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=employee.models.StorePositionsChoises),
        ),
        migrations.DeleteModel(
            name='EmployeePosition',
        ),
    ]
