# Generated by Django 5.1.5 on 2025-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_emploee_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpositions',
            name='district_position',
            field=models.CharField(blank=True, choices=[('DM', 'District Manager'), ('DMT', 'District Manager Tranee'), ('RMT', 'Region Manager Trainee'), ('RM', 'Region Manager'), ('CM', 'Country Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='office_positions',
            field=models.CharField(blank=True, choices=[('BKS', 'Store bookkeper'), ('BKL', 'Logistic bookkeper'), ('BKE', 'Employee bookkeper'), ('BKM', 'Main bookkeper'), ('LS', 'Logigstic Supporter'), ('IT', 'Sys Admin'), ('AU', 'Auditor'), ('FA', 'Facility')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='region_positions',
            field=models.CharField(blank=True, choices=[('DM', 'District Manager'), ('DMT', 'District Manager Tranee'), ('RMT', 'Region Manager Trainee'), ('RM', 'Region Manager'), ('CM', 'Country Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allpositions',
            name='store_posions',
            field=models.CharField(blank=True, choices=[('SM', 'Store Manager'), ('SMT', 'Store Manager Trainee'), ('DepSm', 'DeputyStoreManager'), ('AR', 'Area Responsible'), ('LR', 'Logistic Responsible'), ('SA', 'Sails Assistens')], max_length=50, null=True),
        ),
    ]
