# Generated by Django 5.1.5 on 2025-02-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_allpositions_district_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploee',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.allpositions'),
        ),
    ]
