# Generated by Django 5.1.5 on 2025-02-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_allpositions_district_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllPositions',
            new_name='EmployeePosition',
        ),
    ]
