# Generated by Django 5.1.5 on 2025-02-17 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_districtpositions_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emploee',
            new_name='OfficeEmployee',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='district_position',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='office_positions',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='region_positions',
        ),
        migrations.RemoveField(
            model_name='employeeposition',
            name='store_posions',
        ),
        migrations.AlterField(
            model_name='officeemployee',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.officepositions'),
        ),
        migrations.RenameModel(
            old_name='DistrictPositions',
            new_name='RetailPositions',
        ),
        migrations.CreateModel(
            name='RetailEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.retailpositions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.storepositions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegionPositions',
        ),
        migrations.DeleteModel(
            name='EmployeePosition',
        ),
    ]
