# Generated by Django 5.1.5 on 2025-02-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_district_oficedepartmens_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeemployee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='retailemployee',
            name='location',
        ),
        migrations.RenameField(
            model_name='officeemployee',
            old_name='location',
            new_name='departament',
        ),
        migrations.AddField(
            model_name='retailemployee',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.district'),
        ),
        migrations.AddField(
            model_name='retailemployee',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.region'),
        ),
        migrations.AddField(
            model_name='storeemployee',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.store'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
