# Generated by Django 5.1.5 on 2025-02-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_platformuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformUser',
        ),
    ]
