# Generated by Django 5.1.5 on 2025-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articke',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
