# Generated by Django 5.1.5 on 2025-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articke',
            name='permission',
            field=models.CharField(choices=[('distric', 'Distric'), ('region', 'Region'), ('all', 'All')], default='all', max_length=50),
        ),
    ]
