# Generated by Django 5.1.5 on 2025-04-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesOld',
        ),
    ]
