# Generated by Django 5.1.5 on 2025-02-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0003_articke_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articke',
            name='content',
            field=models.TextField(),
        ),
    ]
