# Generated by Django 5.1.5 on 2025-02-21 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0004_alter_articke_content'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comunication.articke'),
        ),
    ]
