# Generated by Django 5.1.5 on 2025-02-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0007_deletehistory'),
        ('tasks', '0016_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletehistory',
            name='article',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comunication.articke', to_field='title'),
        ),
        migrations.AlterField(
            model_name='deletehistory',
            name='task',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task', to_field='title'),
        ),
    ]
