# Generated by Django 5.1.5 on 2025-02-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0009_alter_deletehistory_article_alter_deletehistory_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletehistory',
            name='task',
        ),
    ]
