# Generated by Django 5.1.5 on 2025-02-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0011_deletehistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletehistory',
            name='coment',
            field=models.BooleanField(default=False),
        ),
    ]
