# Generated by Django 5.1.5 on 2025-03-01 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0014_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
