# Generated by Django 5.1.5 on 2025-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0016_alter_notes_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
