# Generated by Django 5.1.5 on 2025-03-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0018_deletehistory_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletehistory',
            options={'ordering': ['-time_action']},
        ),
    ]
