# Generated by Django 5.1.5 on 2025-03-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0020_articke_image_articke_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articke',
            name='video',
        ),
    ]
