# Generated by Django 5.1.5 on 2025-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0021_remove_articke_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(),
        ),
    ]
