# Generated by Django 5.1.5 on 2025-03-06 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0022_alter_notes_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='NotesOld',
        ),
    ]
