# Generated by Django 5.1.5 on 2025-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskusers_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskusers',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
