# Generated by Django 5.1.5 on 2025-02-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_taskusers_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskusers',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskusers',
            name='not_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
