# Generated by Django 5.1.5 on 2025-02-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_taskusers_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskusers',
            name='completed',
        ),
    ]
