# Generated by Django 5.1.5 on 2025-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_taskusers_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskusers',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
