# Generated by Django 5.1.5 on 2025-02-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskusers_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskusers',
            old_name='end_date',
            new_name='completed_date',
        ),
    ]
