# Generated by Django 5.1.5 on 2025-02-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_end_date_taskusers_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='taskusers',
            options={'ordering': ['completed', 'task__deadline']},
        ),
    ]
