# Generated by Django 5.1.5 on 2025-07-04 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='language',
            field=models.CharField(choices=[('EN', 'english'), ('UA', 'ukraine')], default='UA'),
        ),
        migrations.AddField(
            model_name='education',
            name='about',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='about',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AddField(
            model_name='projects',
            name='about',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AddField(
            model_name='skills',
            name='about',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
    ]
