# Generated by Django 5.1.5 on 2025-06-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('css_class', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.iconclass'),
        ),
        migrations.AddField(
            model_name='links',
            name='icon',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.iconclass'),
        ),
    ]
