# Generated by Django 5.1.5 on 2025-07-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutme_language_education_about_hobbies_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='about',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='about',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='about',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='about',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='education',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.education'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hobies',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.hobbies'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='projects',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.projects'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.skills'),
        ),
    ]
