# Generated by Django 5.1.5 on 2025-06-27 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_iconclass_instrument_icon_links_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='icon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='about.iconclass'),
        ),
        migrations.AlterField(
            model_name='links',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.iconclass'),
        ),
    ]
