# Generated by Django 5.1.5 on 2025-06-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_instrument_icon_alter_links_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='about.iconclass'),
        ),
    ]
