# Generated by Django 5.1.5 on 2025-07-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_education_about_remove_hobbies_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='education',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='hobies',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='language',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='skills',
        ),
    ]
