# Generated by Django 5.1.5 on 2025-07-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_aboutme_education_remove_aboutme_hobies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='education',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.education'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='hobies',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.hobbies'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='language',
            field=models.CharField(choices=[('EN', 'english'), ('UA', 'ukraine')], default='UA'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='projects',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.projects'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='skills',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.skills'),
        ),
    ]
