# Generated by Django 5.1.5 on 2025-07-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutme_education_aboutme_hobies_aboutme_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='projects',
        ),
        migrations.AddField(
            model_name='projects',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
    ]
