# Generated by Django 5.1.5 on 2025-07-04 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_aboutme_projects_projects_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='education',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='hobies',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='skills',
        ),
        migrations.AddField(
            model_name='education',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AddField(
            model_name='hobbies',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AddField(
            model_name='skills',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
    ]
