# Generated by Django 5.1.5 on 2025-07-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_projects_options_remove_aboutme_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutme'),
        ),
    ]
