# Generated by Django 5.1.5 on 2025-07-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_education_about_alter_hobbies_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.iconclass'),
        ),
    ]
