# Generated by Django 5.1.5 on 2025-05-07 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='code',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Must be more then 2 characters')]),
        ),
    ]
