# Generated by Django 5.1.5 on 2025-04-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
