# Generated by Django 5.1.5 on 2025-03-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_alter_topic_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
    ]
