# Generated by Django 5.1.5 on 2025-03-04 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_rename_title_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 19, 9, 27, 239797, tzinfo=datetime.timezone.utc)),
        ),
    ]
