# Generated by Django 5.1.5 on 2025-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_topic_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
