# Generated by Django 5.1.5 on 2025-03-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_remove_section_code_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-add_date']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-add_date']},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='content',
            new_name='description',
        ),
    ]
