# Generated by Django 5.1.5 on 2025-03-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_alter_section_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='topic',
        ),
        migrations.AddField(
            model_name='links',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notebook.section'),
            preserve_default=False,
        ),
    ]
