# Generated by Django 5.1.5 on 2025-03-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0010_alter_code_add_date_alter_links_add_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='short_description',
        ),
    ]
