# Generated by Django 5.1.5 on 2025-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_alter_code_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
