# Generated by Django 5.1.5 on 2025-03-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0014_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
