# Generated by Django 5.1.5 on 2025-03-06 10:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0015_links_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
