# Generated by Django 5.1.5 on 2025-03-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0016_image_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='image_description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='image_title',
        ),
    ]
