# Generated by Django 5.1.5 on 2025-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0020_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_title',
            field=models.CharField(max_length=150),
        ),
    ]
