# Generated by Django 5.1.5 on 2025-03-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0021_alter_image_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
