# Generated by Django 5.1.5 on 2025-03-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0022_alter_links_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
